Registrar/Models/Department.cs
using System.Collections.Generic;

namespace Registrar.Models
{
  public class Department
  {
    public Department()
    {
      this.Courses = new HashSet<DepartmentCourseStudent>();
    }

    public int DepartmentId { get; set; }
    public string DepartmentName { get; set; }
    public virtual ICollection<DepartmentCourseStudent> Courses { get; set; }
  }
}

Registrar/Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using Registrar.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Registrar.Controllers
{
  public class CoursesController : Controller
  {
    private readonly RegistrarContext _db;

    public CoursesController(RegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Course> model = _db.Courses.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "DepartmentName");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Course course, int DepartmentId)
    {
      _db.Courses.Add(course);
      if (DepartmentId != 0)
      {
        _db.DepartmentCourseStudent.Add(new DepartmentCourseStudent() { DepartmentId = DepartmentId, CourseId = course.CourseId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisCourse = _db.Courses
        .Include(course => course.StudentsDepartments)
          .ThenInclude(join => join.Student)
        .Include(course => course.StudentsDepartments)
          .ThenInclude(join => join.Department)
        .FirstOrDefault(course => course.CourseId == id);
      // ViewBag.Department = _db.Departments.FirstOrDefault(departments => departments.DepartmentId == thisCourse.DepartmentId);
      return View(thisCourse);
    }

    public ActionResult Edit(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost]
    public ActionResult Edit(Course course)
    {
      _db.Entry(course).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddDepartment(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(courses => courses.CourseId == id);
      ViewBag.DepartmentId = new SelectList(_db.Departments, "DepartmentId", "DepartmentName");
      return View(thisCourse);
    }
    [HttpPost]
    public ActionResult AddDepartment(Course course, int DepartmentId)
    {
      if (DepartmentId != 0)
      {
        _db.DepartmentCourseStudent.Add(new DepartmentCourseStudent() { DepartmentId = DepartmentId, CourseId = course.CourseId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      return View(thisCourse);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisCourse = _db.Courses.FirstOrDefault(course => course.CourseId == id);
      _db.Courses.Remove(thisCourse);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Registrar/Controllers/DepartmentsController.cs
using Microsoft.AspNetCore.Mvc;
using Registrar.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace Registrar.Controllers
{
  public class DepartmentsController : Controller
  {
    private readonly RegistrarContext _db;

    public DepartmentsController(RegistrarContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Department> model = _db.Departments.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Department department)
    {
      _db.Departments.Add(department);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      var thisDepartment = _db.Departments
        .Include(department => department.Courses).ThenInclude(join => join.Course)
        // .Include(department => department.Students).ThenInclude(join => join.Student)
        .FirstOrDefault(department => department.DepartmentId == id);
      return View(thisDepartment);
    }

    public ActionResult Edit(int id)
    {
      var thisDepartment = _db.Departments.FirstOrDefault(department => department.DepartmentId == id);
      return View(thisDepartment);
    }

    [HttpPost]
    public ActionResult Edit(Department department)
    {
      _db.Entry(department).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      var thisDepartment = _db.Departments.FirstOrDefault(department => department.DepartmentId == id);
      return View(thisDepartment);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      var thisDepartment = _db.Departments.FirstOrDefault(department => department.DepartmentId == id);
      _db.Departments.Remove(thisDepartment);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Registrar/Views/Departments/Create.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Department

<h4>Add a new department</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.DepartmentName)
    @Html.TextBoxFor(model => model.DepartmentName, new {@class="form-control"})
    <input type="submit" value="Add new department" class="btn btn-outline-dark" />
}
<p>@Html.ActionLink("Show all departments", "Index")</p>

Registrar/Views/Departments/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Department

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.DepartmentName): @Html.DisplayFor(model => model.DepartmentName)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" class="btn btn-outline-dark" />
}
@Html.ActionLink("Back to department", "Index")

Registrar/Views/Departments/Details.cshtml
@{
  Layout = "_Layout";
}

@model Registrar.Models.Department;

<h2>Department Details</h2>
<hr />
<h3>@Html.DisplayFor(model => model.DepartmentName)</h3>
<hr>

@if(@Model.Courses.Count == 0)
{
  <p>This department does not contain any courses</p>
}
else
{
  <h4>Courses this department contains:</h4>
  <ul>
  @foreach(var join in Model.Courses)
  {
    <li>@Html.ActionLink(@join.Course.CourseName, "Details", "Courses", new { id = join.CourseId })</li>
  }
  </ul>
}

<p>@Html.ActionLink("Add course to this department", "Create", "Courses")</p>
<p>@Html.ActionLink("Back to departments", "Index")</p>
<p>@Html.ActionLink("Edit department", "Edit", new { id = Model.DepartmentId })</p>
<p>@Html.ActionLink("Delete department", "Delete", new { id = Model.DepartmentId })</p>

Registrar/Views/Departments/Index.cshtml
@{
  Layout = "_Layout";
}

@using Registrar.Models;
@model List<Registrar.Models.Department>;

<h1>University Departments</h1>

@if (@Model.Count == 0)
{
  <h3>No departments have been added yet!</h3>
} 

@foreach (Department department in Model)
{
  <li>@Html.ActionLink($"{department.DepartmentName}", "Details", new { id = department.DepartmentId })</li>
}
<hr>
<p>@Html.ActionLink("Add new department", "Create")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>